# Docker image with scipy, numpy
# and profiling tools: line_profiler, memory_profiler, psutil, guppy3
# build for delitos_CDMX

FROM jupyter/scipy-notebook:dc9744740e12

COPY . .

RUN pip install -r requirements.txt
